route:
  receiver: "Mail Alert"
  group_by: [alertname]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: "Mail Alert"
    email_configs:
      - smarthost: "..." # SMTP server. Ex: smtp.gmail.com:587
        auth_username: "..." # SMTP username
        auth_password: "..." # SMTP password
        from: "prometheus@alertmanager.com"
        to: "..." # Email address to send alerts to
        headers:
          subject: "Prometheus Mail Alerts"
