services:
  alertmanager:
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    image: prom/alertmanager:latest
    networks:
      - prometheus
    restart: always
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager:/alertmanager

  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - '${GRAFANA_PORT}:3000'
    restart: always
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

  node-exporter:
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    image: prom/node-exporter:latest
    networks:
      - prometheus
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    image: prom/prometheus:latest
    networks:
      - grafana
      - prometheus
    restart: always
    volumes:
      - prometheus:/prometheus
      - ./prometheus:/etc/prometheus

networks:
  grafana:
  nginx:
  prometheus:


volumes:
  alertmanager:
  grafana:
  prometheus:
